version: '3.8'

services:
  web:
    build: ./
    command: gunicorn -w 4 -b 0.0.0.0 'server:app'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres:15
    volumes:
      - postgres_data_new:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data_new: