"""empty message

Revision ID: ce171d97b25b
Revises: 91b994ab6159
Create Date: 2023-01-24 22:25:49.712083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce171d97b25b'
down_revision = '91b994ab6159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abstract_algebra', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('abstract_algebra')

    # ### end Alembic commands ###
