version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - 5432:5432